# Exploring US Births

This juptyer notebook is based on a guided project from [DataQuest](https://www.dataquest.io), a data analytics tutorial.

The data comes from a [FiveThirtyEight](https://fivethirtyeight.com/) analysis, [Some People Are Too Superstitious to Have a Baby on Friday the 13th](https://github.com/fivethirtyeight/data/tree/master/births).

## Scope

In this project, I'll analyze CDC and SSA data to determine the frequency of births by

- year,
- month,
- day of the month,
- and day of the week.

# Making a list...

I'll start by reading both datasets into lists, and then creating a list of those lists:

In [1]:
import csv
import requests

CDC_CSV_URL_1 = 'https://raw.githubusercontent.com/fivethirtyeight/data/master/births/US_births_1994-2003_CDC_NCHS.csv'
SSA_CSV_URL_2 = 'https://raw.githubusercontent.com/fivethirtyeight/data/master/births/US_births_2000-2014_SSA.csv'

seeEssVees = [CDC_CSV_URL_1, SSA_CSV_URL_2]
listOfLists = []

for each in seeEssVees:
    with requests.Session() as s:
        download = s.get(each)
        decoded_content = download.content.decode('utf-8')
        data = csv.reader(decoded_content.splitlines(), delimiter=',')
        listOfLists.append(list(data))

# Checking it twice...

The first element of each list should be a header row describing the datapoints that follow:

In [2]:
listOfLists[0][0:5]

[['year', 'month', 'date_of_month', 'day_of_week', 'births'],
 ['1994', '1', '1', '6', '8096'],
 ['1994', '1', '2', '7', '7772'],
 ['1994', '1', '3', '1', '10142'],
 ['1994', '1', '4', '2', '11248']]

In [3]:
listOfLists[1][0:5]

[['year', 'month', 'date_of_month', 'day_of_week', 'births'],
 ['2000', '1', '1', '6', '9083'],
 ['2000', '1', '2', '7', '8006'],
 ['2000', '1', '3', '1', '11363'],
 ['2000', '1', '4', '2', '13032']]

# Benchmarking...

Both datasets contain datapoints for the years 2000 - 2003. Presumably, the number of CDC and SSA records should match. 

The code below checks whether this is the case:

In [4]:
checkListCDC = []
checkListSSA = []

for each in listOfLists[0]:
    try:
        year = int(each[0])
        if (2000 <= year) and (year < 2004):
            checkListCDC.append(each)
    except:
        pass
    
for each in listOfLists[1]:
    try:
        year = int(each[0])
        if (2000 <= year) and (year < 2004):
            checkListSSA.append(each)
    except:
        pass


print("It's",(len(checkListSSA) == len(checkListCDC)),"that both lists have the same number of elements:")
print("The CDC data has",len(checkListCDC), "observations for the years 2000-2003.")
print("The SSA data has",len(checkListSSA), "observations for the years 2000-2003.")

It's True that both lists have the same number of elements:
The CDC data has 1461 observations for the years 2000-2003.
The SSA data has 1461 observations for the years 2000-2003.

# More Benchmarking...

Both datasets contain the same *number* of datapoints for the years 2000 - 2003. But are those data points the same?

The code below compares the first five observations:

In [5]:
checkListCDC[0:5]

[['2000', '1', '1', '6', '8843'],
 ['2000', '1', '2', '7', '7816'],
 ['2000', '1', '3', '1', '11123'],
 ['2000', '1', '4', '2', '12703'],
 ['2000', '1', '5', '3', '12240']]

In [6]:
checkListSSA[0:5]

[['2000', '1', '1', '6', '9083'],
 ['2000', '1', '2', '7', '8006'],
 ['2000', '1', '3', '1', '11363'],
 ['2000', '1', '4', '2', '13032'],
 ['2000', '1', '5', '3', '12558']]

# Counting Function

There are differences in the number of births recorded by each dataset, so we should analyze them separately.

Rather than write code to analyze each dataset separately, the code below creates a function that sums the number of births by year, month, day of the month, and day of the week.

In [7]:
import pprint

def calc_counts(data, column):
    totalBirths = {}
    for each in data:
        try:
            period = int(each[column])
            if period in totalBirths:
                totalBirths[period]+=int(each[4])
            else:
                totalBirths[period]=int(each[4])
        except:
            pass
    return totalBirths

for each1 in listOfLists:
    print("")
    print("New dataset begins below:")
    for i in range(4):
        print("")
        if i == 0:
            print("Years:")
        elif i == 1:
            print("Month:")
        elif i == 2:
            print("Day of Month:")
        else:
            print("Day of Week:")
                
        print("")
        pprint.pprint(calc_counts(each1,i))

New dataset begins below:

Years:

{1994: 3952767,
 1995: 3899589,
 1996: 3891494,
 1997: 3880894,
 1998: 3941553,
 1999: 3959417,
 2000: 4058814,
 2001: 4025933,
 2002: 4021726,
 2003: 4089950}

Month:

{1: 3232517,
 2: 3018140,
 3: 3322069,
 4: 3185314,
 5: 3350907,
 6: 3296530,
 7: 3498783,
 8: 3525858,
 9: 3439698,
 10: 3378814,
 11: 3171647,
 12: 3301860}

Day of Month:

{1: 1276557,
 2: 1288739,
 3: 1304499,
 4: 1288154,
 5: 1299953,
 6: 1304474,
 7: 1310459,
 8: 1312297,
 9: 1303292,
 10: 1320764,
 11: 1314361,
 12: 1318437,
 13: 1277684,
 14: 1320153,
 15: 1319171,
 16: 1315192,
 17: 1324953,
 18: 1326855,
 19: 1318727,
 20: 1324821,
 21: 1322897,
 22: 1317381,
 23: 1293290,
 24: 1288083,
 25: 1272116,
 26: 1284796,
 27: 1294395,
 28: 1307685,
 29: 1223161,
 30: 1202095,
 31: 746696}

Day of Week:

{1: 5789166,
 2: 6446196,
 3: 6322855,
 4: 6288429,
 5: 6233657,
 6: 4562111,
 7: 4079723}

New dataset begins below:

Years:

{2000: 4149598,
 2001: 4110963,
 2002: 4099313,
 2003: 4163060,
 2004: 4186863,
 2005: 4211941,
 2006: 4335154,
 2007: 4380784,
 2008: 4310737,
 2009: 4190991,
 2010: 4055975,
 2011: 4006908,
 2012: 4000868,
 2013: 3973337,
 2014: 4010532}

Month:

{1: 5072588,
 2: 4725693,
 3: 5172961,
 4: 4960750,
 5: 5195445,
 6: 5163360,
 7: 5450418,
 8: 5540170,
 9: 5399592,
 10: 5302865,
 11: 5008750,
 12: 5194432}

Day of Month:

{1: 2003627,
 2: 2030447,
 3: 2042441,
 4: 2004785,
 5: 2036185,
 6: 2037729,
 7: 2063416,
 8: 2061652,
 9: 2044600,
 10: 2066154,
 11: 2054098,
 12: 2072483,
 13: 2000064,
 14: 2076291,
 15: 2066999,
 16: 2058651,
 17: 2071572,
 18: 2077673,
 19: 2065328,
 20: 2083247,
 21: 2079198,
 22: 2051012,
 23: 2023555,
 24: 1993203,
 25: 1972534,
 26: 2001311,
 27: 2035483,
 28: 2051528,
 29: 1918965,
 30: 1879925,
 31: 1162868}

Day of Week:

{1: 9316001,
 2: 10274874,
 3: 10109130,
 4: 10045436,
 5: 9850199,
 6: 6704495,
 7: 5886889}

## Better Output

So far, we've found the number of births over certain periods. In the output above, integers represent certain days of the week (1-7, with 1 being a Monday) or months of the year (1-12).

Since we know the data pretty well at this point, this isn't a problem. But if someone like Blake in Marketing sees the output in this format, he's going to shoot us a quick e-email asking if we can meet for coffee to discuss it.

Too much caffeine is bad for us, and nobody reads e-mails, so we'll make the output more user-friendly for Blake by renaming the days of the week and the months of the year with the code below:

In [8]:
for dataSet in listOfLists:
    for each in dataSet:
        try:
            month = int(each[1])
            if month == 1:
                each[1] = "January"
            elif month == 2:
                each[1] = "Febraury"
            elif month == 3:
                each[1] = "March"
            elif month == 4:
                each[1] = "April"
            elif month == 5:
                each[1] = "May"
            elif month == 6:
                each[1] = "June"
            elif month == 7:
                each[1] = "July"
            elif month == 8:
                each[1] = "August"
            elif month == 9:
                each[1] = "September"
            elif month == 10:
                each[1] = "October"
            elif month == 11:
                each[1] = "November"
            else:
                each[1] = "December"
        except:
            pass
        
for dataSet in listOfLists:
    for each in dataSet:
        try:
            DOW = int(each[3])
            if DOW == 1:
                each[3]= "Monday"
            elif DOW == 2:
                each[3]= "Tuesday"
            elif DOW == 3:
                each[3]= "Wednesday"
            elif DOW == 4:
                each[3] = "Thursday"
            elif DOW == 5:
                each[3] = "Friday"
            elif DOW == 6:
                each[3] = "Saturday"
            else:
                each[3] = "Sunday"
        except:
            pass

for dataSet in listOfLists:
    print("")
    print("New dataset begins below:")
    print("")
    for each in dataSet[0:10]:
        print(each)

New dataset begins below:

['year', 'month', 'date_of_month', 'day_of_week', 'births']
['1994', 'January', '1', 'Saturday', '8096']
['1994', 'January', '2', 'Sunday', '7772']
['1994', 'January', '3', 'Monday', '10142']
['1994', 'January', '4', 'Tuesday', '11248']
['1994', 'January', '5', 'Wednesday', '11053']
['1994', 'January', '6', 'Thursday', '11406']
['1994', 'January', '7', 'Friday', '11251']
['1994', 'January', '8', 'Saturday', '8653']
['1994', 'January', '9', 'Sunday', '7910']

New dataset begins below:

['year', 'month', 'date_of_month', 'day_of_week', 'births']
['2000', 'January', '1', 'Saturday', '9083']
['2000', 'January', '2', 'Sunday', '8006']
['2000', 'January', '3', 'Monday', '11363']
['2000', 'January', '4', 'Tuesday', '13032']
['2000', 'January', '5', 'Wednesday', '12558']
['2000', 'January', '6', 'Thursday', '12466']
['2000', 'January', '7', 'Friday', '12516']
['2000', 'January', '8', 'Saturday', '8934']
['2000', 'January', '9', 'Sunday', '7949']

Now that out data is in a more user-friendly format, we can run the counting function again:

In [10]:
import pprint

def calc_counts(data, column):
    totalBirths = {}
    for each in data[1:]:
        try:
            period = each[column]
            if period in totalBirths:
                totalBirths[period]+=int(each[4])
            else:
                totalBirths[period]=int(each[4])
        except:
            pass
    return totalBirths

for each1 in listOfLists:
    print("")
    print("New dataset begins below:")
    for i in range(4):
        print("")
        if i == 0:
            print("Year:")
        elif i == 1:
            print("Month:")
        elif i == 2:
            print("Day of Month:")
        else:
            print("Day of Week:")
                
        print("")
        pprint.pprint(calc_counts(each1,i))

New dataset begins below:

Years:

{'1994': 3952767,
 '1995': 3899589,
 '1996': 3891494,
 '1997': 3880894,
 '1998': 3941553,
 '1999': 3959417,
 '2000': 4058814,
 '2001': 4025933,
 '2002': 4021726,
 '2003': 4089950}

Month:

{'April': 3185314,
 'August': 3525858,
 'December': 3301860,
 'Febraury': 3018140,
 'January': 3232517,
 'July': 3498783,
 'June': 3296530,
 'March': 3322069,
 'May': 3350907,
 'November': 3171647,
 'October': 3378814,
 'September': 3439698}

Day of Month:

{'1': 1276557,
 '10': 1320764,
 '11': 1314361,
 '12': 1318437,
 '13': 1277684,
 '14': 1320153,
 '15': 1319171,
 '16': 1315192,
 '17': 1324953,
 '18': 1326855,
 '19': 1318727,
 '2': 1288739,
 '20': 1324821,
 '21': 1322897,
 '22': 1317381,
 '23': 1293290,
 '24': 1288083,
 '25': 1272116,
 '26': 1284796,
 '27': 1294395,
 '28': 1307685,
 '29': 1223161,
 '3': 1304499,
 '30': 1202095,
 '31': 746696,
 '4': 1288154,
 '5': 1299953,
 '6': 1304474,
 '7': 1310459,
 '8': 1312297,
 '9': 1303292}

Day of Week:

{'Friday': 6233657,
 'Monday': 5789166,
 'Saturday': 4562111,
 'Sunday': 4079723,
 'Thursday': 6288429,
 'Tuesday': 6446196,
 'Wednesday': 6322855}

New dataset begins below:

Years:

{'2000': 4149598,
 '2001': 4110963,
 '2002': 4099313,
 '2003': 4163060,
 '2004': 4186863,
 '2005': 4211941,
 '2006': 4335154,
 '2007': 4380784,
 '2008': 4310737,
 '2009': 4190991,
 '2010': 4055975,
 '2011': 4006908,
 '2012': 4000868,
 '2013': 3973337,
 '2014': 4010532}

Month:

{'April': 4960750,
 'August': 5540170,
 'December': 5194432,
 'Febraury': 4725693,
 'January': 5072588,
 'July': 5450418,
 'June': 5163360,
 'March': 5172961,
 'May': 5195445,
 'November': 5008750,
 'October': 5302865,
 'September': 5399592}

Day of Month:

{'1': 2003627,
 '10': 2066154,
 '11': 2054098,
 '12': 2072483,
 '13': 2000064,
 '14': 2076291,
 '15': 2066999,
 '16': 2058651,
 '17': 2071572,
 '18': 2077673,
 '19': 2065328,
 '2': 2030447,
 '20': 2083247,
 '21': 2079198,
 '22': 2051012,
 '23': 2023555,
 '24': 1993203,
 '25': 1972534,
 '26': 2001311,
 '27': 2035483,
 '28': 2051528,
 '29': 1918965,
 '3': 2042441,
 '30': 1879925,
 '31': 1162868,
 '4': 2004785,
 '5': 2036185,
 '6': 2037729,
 '7': 2063416,
 '8': 2061652,
 '9': 2044600}

Day of Week:

{'Friday': 9850199,
 'Monday': 9316001,
 'Saturday': 6704495,
 'Sunday': 5886889,
 'Thursday': 10045436,
 'Tuesday': 10274874,
 'Wednesday': 10109130}

# More Functions

Write a function that can calculate the min and max values for any dictionary that's passed in.
Write a function that extracts the same values across years and calculates the differences between consecutive values to show if number of births is increasing or decreasing.
For example, how did the number of births on Saturday change each year between 1994 and 2003?
Find a way to combine the CDC data with the SSA data, which you can find here. Specifically, brainstorm ways to deal with the overlapping time periods in the datasets.